# Generated by Django 4.2.4 on 2023-08-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
        migrations.AddField(
            model_name='user',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
